### ISSUE TITLE
add links to doxygen docs to homepage

### ISSUE THREAD

**Issue by ChristineStawitz-NOAA** [NOAA-FIMS/noaa-fims.github.io#1]

**Comment by iantaylor-NOAA** [comment]
This was completed by @ChristineStawitz-NOAA in 04b1d3812ee6bd5501882074137c8f38efeef58d the week after the issue was opened. The link says "View the C++ documentation" so if someone is searching for "doxygen" they wouldn't find it, but I think that's OK.
